# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('closing_price', models.IntegerField(default=0)),
                ('predicted_price', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('yesterday_date', models.DateField(auto_now_add=True)),
                ('previous_closing_price', models.IntegerField(default=0)),
                ('increased_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
